Fix pygame.error: Couldn't open data/data/0.jpg
Traceback (most recent call last):
  File "/usr/share/sugar/activities/jamath.activity/sugargame/canvas.py", line 65, in _run_pygame_cb
    main_fn()
  File "/usr/share/sugar/activities/jamath.activity/juego.py", line 254, in run
    self.play(level)
  File "/usr/share/sugar/activities/jamath.activity/juego.py", line 186, in play
    fondo = [load_image("data/" + str(x) + ".jpg") for x in range(0,NUM_IMAGES)]
  File "/usr/share/sugar/activities/jamath.activity/juego.py", line 261, in load_image
    return pygame.image.load(path).convert_alpha()
pygame.error: Couldn't open data/data/0.jpg

Introduced by commit 183ace7